/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountDown: typeof import('./components/countDown/countDown.vue')['default']
    CountDownBirthday: typeof import('./components/countDown/CountDownBirthday.vue')['default']
    CountDownBox: typeof import('./components/countDown/CountDownBox.vue')['default']
    CountDownBoxEidAlAdha: typeof import('./components/countDown/CountDownBoxEidAlAdha.vue')['default']
    CountDownBoxRamadan: typeof import('./components/countDown/CountDownBoxRamadan.vue')['default']
    CountDownCp: typeof import('./components/countDown/CountDownCp.vue')['default']
    CountDownDragon: typeof import('./components/countDown/CountDownDragon.vue')['default']
    CustomTable: typeof import('./components/customTable/customTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImagePreview: typeof import('./components/ImagePreview/ImagePreview.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    NavBar: typeof import('./components/navBar/navBar.vue')['default']
    PopupView01: typeof import('./components/popupView01/popupView01.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SanaAutoText: typeof import('./components/sanaAutoText/index.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanList: typeof import('vant/es')['List']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
